read_from:
  catalog_name: samples
  schema_name: nyctaxi
  table_name: trips

catalog_name: sandbox
schema_name: sb_adan

num_features:
  - trip_distance

cat_features:
  - pickup_zip
  - dropoff_zip

target: fare_amount
