catalog_name: samples
schema_name: nyctaxi
table_name: trips

databricks:
  profile_id: ${DATABRICKS_WORKSPACE_ID}

data:
  input_path: "samples.nyctaxi.trips"

num_features:
  - trip_distance

cat_features:
  - pickup_zip
  - dropoff_zip

target: fare_amount
